//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipboardHelperRegEx.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipboardHelperRegEx.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon activatedForDarkTheme {
            get {
                object obj = ResourceManager.GetObject("activatedForDarkTheme", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon activatedForLightTheme {
            get {
                object obj = ResourceManager.GetObject("activatedForLightTheme", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///  &lt;xsd:element name=&quot;AutoShownTabs&quot; type=&quot;AutoShownTabs&quot;/&gt;
        ///
        ///  &lt;xsd:complexType name=&quot;AutoShownTabs&quot;&gt;
        ///    &lt;xsd:sequence minOccurs=&quot;1&quot; maxOccurs=&quot;1&quot;&gt;
        ///      &lt;xsd:element name=&quot;List&quot;  type=&quot;ListType&quot; /&gt;
        ///    &lt;/xsd:sequence&gt;
        ///  &lt;/xsd:complexType&gt;
        ///
        ///  &lt;xsd:complexType name=&quot;ListType&quot;&gt;
        ///    &lt;xsd:sequence minOccurs=&quot;1&quot; maxOccurs=&quot;1000&quot; &gt;
        ///      &lt;xsd:element name=&quot;AutoShownTab&quot; t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AutoXmlSchema {
            get {
                return ResourceManager.GetString("AutoXmlSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Closed {
            get {
                object obj = ResourceManager.GetObject("Closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ClosedSelected {
            get {
                object obj = ResourceManager.GetObject("ClosedSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon deactivatedForDarkTheme {
            get {
                object obj = ResourceManager.GetObject("deactivatedForDarkTheme", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon deactivatedForLightTheme {
            get {
                object obj = ResourceManager.GetObject("deactivatedForLightTheme", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon dynamicIcon1ForDarkTheme {
            get {
                object obj = ResourceManager.GetObject("dynamicIcon1ForDarkTheme", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon dynamicIcon1ForLightTheme {
            get {
                object obj = ResourceManager.GetObject("dynamicIcon1ForLightTheme", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon dynamicIcon2ForDarkTheme {
            get {
                object obj = ResourceManager.GetObject("dynamicIcon2ForDarkTheme", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon dynamicIcon2ForLightTheme {
            get {
                object obj = ResourceManager.GetObject("dynamicIcon2ForLightTheme", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon dynamicIcon3ForDarkTheme {
            get {
                object obj = ResourceManager.GetObject("dynamicIcon3ForDarkTheme", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon dynamicIcon3ForLightTheme {
            get {
                object obj = ResourceManager.GetObject("dynamicIcon3ForLightTheme", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon dynamicIcon4ForDarkTheme {
            get {
                object obj = ResourceManager.GetObject("dynamicIcon4ForDarkTheme", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon dynamicIcon4ForLightTheme {
            get {
                object obj = ResourceManager.GetObject("dynamicIcon4ForLightTheme", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon dynamicIcon5ForDarkTheme {
            get {
                object obj = ResourceManager.GetObject("dynamicIcon5ForDarkTheme", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon dynamicIcon5ForLightTheme {
            get {
                object obj = ResourceManager.GetObject("dynamicIcon5ForLightTheme", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon dynamicIcon6ForDarkTheme {
            get {
                object obj = ResourceManager.GetObject("dynamicIcon6ForDarkTheme", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon dynamicIcon6ForLightTheme {
            get {
                object obj = ResourceManager.GetObject("dynamicIcon6ForLightTheme", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon dynamicIcon7ForDarkTheme {
            get {
                object obj = ResourceManager.GetObject("dynamicIcon7ForDarkTheme", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon dynamicIcon7ForLightTheme {
            get {
                object obj = ResourceManager.GetObject("dynamicIcon7ForLightTheme", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon dynamicIcon8ForDarkTheme {
            get {
                object obj = ResourceManager.GetObject("dynamicIcon8ForDarkTheme", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon dynamicIcon8ForLightTheme {
            get {
                object obj = ResourceManager.GetObject("dynamicIcon8ForLightTheme", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while changing the current form visibility status with a new one..
        /// </summary>
        public static string FormFading_Change_An_error_occured_while_changing_the_current_form_visibility_status_with_a_new_one_ {
            get {
                return ResourceManager.GetString("FormFading_Change_An_error_occured_while_changing_the_current_form_visibility_sta" +
                        "tus_with_a_new_one_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while changing the forms opacity and visibility.
        /// </summary>
        public static string FormFading_FadeFormByChangingOpacity_An_error_occured_while_changing_the_forms_opacity_and_visibility {
            get {
                return ResourceManager.GetString("FormFading_FadeFormByChangingOpacity_An_error_occured_while_changing_the_forms_op" +
                        "acity_and_visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClipboardHelperRegEx information.
        /// </summary>
        public static string GetTextClipboard_Start_Clipboard_Helper_information {
            get {
                return ResourceManager.GetString("GetTextClipboard_Start_Clipboard_Helper_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Clipboard could not get text..
        /// </summary>
        public static string GetTextClipboard_Start_Windows_Clipboard_could_not_get_text_ {
            get {
                return ResourceManager.GetString("GetTextClipboard_Start_Windows_Clipboard_could_not_get_text_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CONTENTS OF THIS FILE - CLIPBOARD HELPER REGEX - April 28, 2020
        ///---------------------------------------------------------------
        ///
        /// * 1.  Introduction
        /// * 2.  Requirements
        /// * 3.  How it Works
        /// * 4.  Features
        /// * 5.  How to use
        /// * 6.  Installation
        /// * 7.  Why use this
        /// * 8.  Settings
        /// * 9.  License
        /// * 10. Built With
        /// * 11. Author
        /// * 12. Project status
        ///
        ///
        ///1. Introduction
        ///---------------
        ///
        ///CLIPBOARD HELPER REGEX can automatically detect if text changes in Windows Clipboard. It can display a list [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LeftArrow {
            get {
                object obj = ResourceManager.GetObject("LeftArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LeftArrowSelected {
            get {
                object obj = ResourceManager.GetObject("LeftArrowSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                     GNU GENERAL PUBLIC LICENSE
        ///                       Version 3, 29 June 2007
        ///
        /// Copyright (C) 2007 Free Software Foundation, Inc. &lt;https://fsf.org/&gt;
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///                            Preamble
        ///
        ///  The GNU General Public License is a free, copyleft license for
        ///software and other kinds of works.
        ///
        ///  The licenses for most software and other practical works are designed
        ///t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when listbox selection was changed: .
        /// </summary>
        public static string ListboxMultiSelection_HandleSelectionChange_An_error_occured_when_listbox_selection_was_changed__ {
            get {
                return ResourceManager.GetString("ListboxMultiSelection_HandleSelectionChange_An_error_occured_when_listbox_selecti" +
                        "on_was_changed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClipboardHelperRegEx error.
        /// </summary>
        public static string ListboxMultiSelection_HandleSelectionChange_Clipboard_Helper_error {
            get {
                return ResourceManager.GetString("ListboxMultiSelection_HandleSelectionChange_Clipboard_Helper_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when getting selection ready: .
        /// </summary>
        public static string ListboxMultiSelection_StripSelectionToOutData_An_error_occured_when_getting_selection_ready__ {
            get {
                return ResourceManager.GetString("ListboxMultiSelection_StripSelectionToOutData_An_error_occured_when_getting_selec" +
                        "tion_ready__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Locked {
            get {
                object obj = ResourceManager.GetObject("Locked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LockedSelected {
            get {
                object obj = ResourceManager.GetObject("LockedSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000000	Officially Xerox
        ///000001	SuperLAN-2U
        ///000002	BBN (was internal usage only, no longer used)
        ///000003	XEROX CORPORATION
        ///000004	XEROX CORPORATION
        ///000005	XEROX CORPORATION
        ///000006	XEROX CORPORATION
        ///000007	XEROX CORPORATION
        ///000008	XEROX CORPORATION
        ///000009	powerpipes?
        ///00000A	OMRON TATEISI ELECTRONICS CO.
        ///00000B	MATRIX CORPORATION
        ///00000C	Cisco
        ///00000D	FIBRONICS LTD.
        ///00000E	Fujitsu
        ///00000F	Next
        ///000010	Hughes
        ///000011	Tektrnix
        ///000012	INFORMATION TECHNOLOGY LIMITED
        ///000013	Camex
        ///000014	Netronix
        ///000015	Datapoint Corporat [rest of string was truncated]&quot;;.
        /// </summary>
        public static string macvendor {
            get {
                return ResourceManager.GetString("macvendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///            elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///  &lt;xsd:element name=&quot;ManuallyShownTabs&quot; type=&quot;ManuallyShownTabs&quot;/&gt;
        ///
        ///  &lt;xsd:complexType name=&quot;ManuallyShownTabs&quot;&gt;
        ///    &lt;xsd:sequence minOccurs=&quot;1&quot; maxOccurs=&quot;1&quot;&gt;
        ///      &lt;xsd:element name=&quot;List&quot;  type=&quot;ListType&quot; /&gt;
        ///    &lt;/xsd:sequence&gt;
        ///  &lt;/xsd:complexType&gt;
        ///
        ///  &lt;xsd:complexType name=&quot;ListType&quot;&gt;
        ///    &lt;xsd:sequence minOccurs=&quot;1&quot; maxOccurs=&quot;50&quot; &gt;
        ///      &lt;xsd:elemen [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ManualXmlSchema {
            get {
                return ResourceManager.GetString("ManualXmlSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap minimize_selected {
            get {
                object obj = ResourceManager.GetObject("minimize_selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap minimize_unselected {
            get {
                object obj = ResourceManager.GetObject("minimize_unselected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when setting program icon static: .
        /// </summary>
        public static string NotifyIcon_SetStatic_An_error_occured_when_setting_program_icon_static__ {
            get {
                return ResourceManager.GetString("NotifyIcon_SetStatic_An_error_occured_when_setting_program_icon_static__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClipboardHelperRegEx error.
        /// </summary>
        public static string NotifyIcon_SetStatic_Clipboard_Helper_error {
            get {
                return ResourceManager.GetString("NotifyIcon_SetStatic_Clipboard_Helper_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while pasting.
        /// </summary>
        public static string Pasting_GlobalHook_KeyDown_An_error_occured_while_pasting {
            get {
                return ResourceManager.GetString("Pasting_GlobalHook_KeyDown_An_error_occured_while_pasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when getting the next item to paste: .
        /// </summary>
        public static string Pasting_RemoveAndReturnFirstLine_An_error_occured_when_getting_the_next_item_to_paste__ {
            get {
                return ResourceManager.GetString("Pasting_RemoveAndReturnFirstLine_An_error_occured_when_getting_the_next_item_to_p" +
                        "aste__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClipboardHelperRegEx error.
        /// </summary>
        public static string Pasting_RemoveAndReturnFirstLine_Clipboard_Helper_error {
            get {
                return ResourceManager.GetString("Pasting_RemoveAndReturnFirstLine_Clipboard_Helper_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while setting the min forms visibility..
        /// </summary>
        public static string PresenterMain_FormHiding_WorkFinished_An_error_occured_while_setting_the_min_forms_visibility_ {
            get {
                return ResourceManager.GetString("PresenterMain_FormHiding_WorkFinished_An_error_occured_while_setting_the_min_form" +
                        "s_visibility_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClipboardHelperRegEx.
        /// </summary>
        public static string PresenterMain_OnLoadView_Clipboard_Helper {
            get {
                return ResourceManager.GetString("PresenterMain_OnLoadView_Clipboard_Helper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when setting value to the clipboard: .
        /// </summary>
        public static string PresenterMain_OnMouseUpNotifyIconProgram_An_error_occured_when_setting_value_to_the_clipboard__ {
            get {
                return ResourceManager.GetString("PresenterMain_OnMouseUpNotifyIconProgram_An_error_occured_when_setting_value_to_t" +
                        "he_clipboard__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while OnMouseUpNotifyIconProgram..
        /// </summary>
        public static string PresenterMain_OnMouseUpNotifyIconProgram_An_error_occured_while_OnMouseUpNotifyIconProgram_ {
            get {
                return ResourceManager.GetString("PresenterMain_OnMouseUpNotifyIconProgram_An_error_occured_while_OnMouseUpNotifyIc" +
                        "onProgram_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClipboardHelperRegEx error.
        /// </summary>
        public static string PresenterMain_OnMouseUpNotifyIconProgram_Clipboard_Helper_error {
            get {
                return ResourceManager.GetString("PresenterMain_OnMouseUpNotifyIconProgram_Clipboard_Helper_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while setting value to the clipboard. Please click OK to continue using ClipboardHelperRegEx
        ///
        ///
        ///Click OK to continue using ClipboardHelperRegEx.
        /// </summary>
        public static string PresenterMain_OnMouseUpNotifyIconProgram_RemoveTextFormatting {
            get {
                return ResourceManager.GetString("PresenterMain_OnMouseUpNotifyIconProgram_RemoveTextFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured.
        /// </summary>
        public static string PresenterMain_OnMouseUpNotifyIconProgram_RemoveTextFormatting_caption {
            get {
                return ResourceManager.GetString("PresenterMain_OnMouseUpNotifyIconProgram_RemoveTextFormatting_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string PresenterMainSplContPanelUpTabs_CreateTabs_Auto {
            get {
                return ResourceManager.GetString("PresenterMainSplContPanelUpTabs_CreateTabs_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasting finished. Please select an item or items in the list..
        /// </summary>
        public static string PresenterMainSplContPanelUpTabs_Pasting_MultipastingDeactivated_Pasting_finished__Please_select_an_item_or_items_in_the_list_ {
            get {
                return ResourceManager.GetString("PresenterMainSplContPanelUpTabs_Pasting_MultipastingDeactivated_Pasting_finished_" +
                        "_Please_select_an_item_or_items_in_the_list_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  out of .
        /// </summary>
        public static string PresenterMainSplContPanelUpTabs_Pasting_PastingOccured__out_of_ {
            get {
                return ResourceManager.GetString("PresenterMainSplContPanelUpTabs_Pasting_PastingOccured__out_of_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  pasted..
        /// </summary>
        public static string PresenterMainSplContPanelUpTabs_Pasting_PastingOccured__pasted_ {
            get {
                return ResourceManager.GetString("PresenterMainSplContPanelUpTabs_Pasting_PastingOccured__pasted_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program wasn&apos;t ready, selection has been cleared. Please select again!.
        /// </summary>
        public static string PresenterMainSplContPanelUpTabs_SelectionErrorCheckPassed_Program_wasn_t_ready__selection_has_been_cleared__Please_select_again_ {
            get {
                return ResourceManager.GetString("PresenterMainSplContPanelUpTabs_SelectionErrorCheckPassed_Program_wasn_t_ready__s" +
                        "election_has_been_cleared__Please_select_again_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste with LEFT CTRL+V. Abort pasting with ESC..
        /// </summary>
        public static string PresenterMainSplContPanelUpTabs_SendPastingClassWithPastableLines_Paste_with_LEFT_CTRL_V__Abort_pasting_with_ESC_ {
            get {
                return ResourceManager.GetString("PresenterMainSplContPanelUpTabs_SendPastingClassWithPastableLines_Paste_with_LEFT" +
                        "_CTRL_V__Abort_pasting_with_ESC_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item or items in the list..
        /// </summary>
        public static string PresenterMainSplContPanelUpTabs_TransformLinesForOneListbox_Please_select_an_item_or_items_in_the_list_ {
            get {
                return ResourceManager.GetString("PresenterMainSplContPanelUpTabs_TransformLinesForOneListbox_Please_select_an_item" +
                        "_or_items_in_the_list_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error (1) occured when setting a new value to listbox: .
        /// </summary>
        public static string PresenterMainSplContPanelUpTabs_TransformLinesForOneSpecificListbox_An_error__1__occured_when_setting_a_new_value_to_listbox__ {
            get {
                return ResourceManager.GetString("PresenterMainSplContPanelUpTabs_TransformLinesForOneSpecificListbox_An_error__1__" +
                        "occured_when_setting_a_new_value_to_listbox__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error (2) occured when setting a new value to listbox: .
        /// </summary>
        public static string PresenterMainSplContPanelUpTabs_TransformLinesForOneSpecificListbox_An_error__2__occured_when_setting_a_new_value_to_listbox__ {
            get {
                return ResourceManager.GetString("PresenterMainSplContPanelUpTabs_TransformLinesForOneSpecificListbox_An_error__2__" +
                        "occured_when_setting_a_new_value_to_listbox__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error (3) occured when setting a new value to listbox: .
        /// </summary>
        public static string PresenterMainSplContPanelUpTabs_TransformLinesForOneSpecificListbox_An_error__3__occured_when_setting_a_new_value_to_listbox__ {
            get {
                return ResourceManager.GetString("PresenterMainSplContPanelUpTabs_TransformLinesForOneSpecificListbox_An_error__3__" +
                        "occured_when_setting_a_new_value_to_listbox__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error (4) occured when setting a new value to listbox: .
        /// </summary>
        public static string PresenterMainSplContPanelUpTabs_TransformLinesForOneSpecificListbox_An_error__4__occured_when_setting_a_new_value_to_listbox__ {
            get {
                return ResourceManager.GetString("PresenterMainSplContPanelUpTabs_TransformLinesForOneSpecificListbox_An_error__4__" +
                        "occured_when_setting_a_new_value_to_listbox__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClipboardHelperRegEx error.
        /// </summary>
        public static string PresenterMainSplContPanelUpTabs_TransformLinesForOneSpecificListbox_Clipboard_Helper_error {
            get {
                return ResourceManager.GetString("PresenterMainSplContPanelUpTabs_TransformLinesForOneSpecificListbox_Clipboard_Hel" +
                        "per_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select another app to paste line. Clear selection with ESC..
        /// </summary>
        public static string PresenterMainSplContPanelUpTabs_TriggerEventsWhetherItemsAreSelectedOrNot_Select_another_app_to_paste_line__Clear_selection_with_ESC_ {
            get {
                return ResourceManager.GetString("PresenterMainSplContPanelUpTabs_TriggerEventsWhetherItemsAreSelectedOrNot_Select_" +
                        "another_app_to_paste_line__Clear_selection_with_ESC_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select another app to paste lines. Clear selection with ESC..
        /// </summary>
        public static string PresenterMainSplContPanelUpTabs_TriggerEventsWhetherItemsAreSelectedOrNot_Select_another_app_to_paste_lines__Clear_selection_with_ESC_ {
            get {
                return ResourceManager.GetString("PresenterMainSplContPanelUpTabs_TriggerEventsWhetherItemsAreSelectedOrNot_Select_" +
                        "another_app_to_paste_lines__Clear_selection_with_ESC_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Clipboard now: .
        /// </summary>
        public static string PresenterMin_Clipboard_Changed_In_Clipboard_now__ {
            get {
                return ResourceManager.GetString("PresenterMin_Clipboard_Changed_In_Clipboard_now__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string PresenterUserSettingsLeftMenu_OnMouseClickNode_Advanced {
            get {
                return ResourceManager.GetString("PresenterUserSettingsLeftMenu_OnMouseClickNode_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string PresenterUserSettingsLeftMenu_OnMouseClickNode_Appearance {
            get {
                return ResourceManager.GetString("PresenterUserSettingsLeftMenu_OnMouseClickNode_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoShownTabs.
        /// </summary>
        public static string PresenterUserSettingsLeftMenu_OnMouseClickNode_AutoShownTabs {
            get {
                return ResourceManager.GetString("PresenterUserSettingsLeftMenu_OnMouseClickNode_AutoShownTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManuallyShownTabs.
        /// </summary>
        public static string PresenterUserSettingsLeftMenu_OnMouseClickNode_ManuallyShownTabs {
            get {
                return ResourceManager.GetString("PresenterUserSettingsLeftMenu_OnMouseClickNode_ManuallyShownTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add CSV data File.
        /// </summary>
        public static string PresenterUserSettingsRightAdvanced__view_AddClickMenu_Add_CSV_data_File {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAdvanced__view_AddClickMenu_Add_CSV_data_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV files|*.csv.
        /// </summary>
        public static string PresenterUserSettingsRightAdvanced__view_AddClickMenu_CSV_files___csv {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAdvanced__view_AddClickMenu_CSV_files___csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace XML settings File.
        /// </summary>
        public static string PresenterUserSettingsRightAdvanced__view_ReplaceClickMenu_Replace_XML_settings_File {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAdvanced__view_ReplaceClickMenu_Replace_XML_settings_Fi" +
                        "le", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML file|AutoShownTabs.xml.
        /// </summary>
        public static string PresenterUserSettingsRightAdvanced__view_ReplaceClickMenu_XML_file_AutoShownTabs_xml {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAdvanced__view_ReplaceClickMenu_XML_file_AutoShownTabs_" +
                        "xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML file|ManuallyShownTabs.xml.
        /// </summary>
        public static string PresenterUserSettingsRightAdvanced__view_ReplaceClickMenu_XML_file_ManuallyShownTabs_xml {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAdvanced__view_ReplaceClickMenu_XML_file_ManuallyShownT" +
                        "abs_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while Dialog_ClickOkMouseButton..
        /// </summary>
        public static string PresenterUserSettingsRightAdvanced_Dialog_ClickOkMouseButton_An_error_occured_while_Dialog_ClickOkMouseButton_ {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAdvanced_Dialog_ClickOkMouseButton_An_error_occured_whi" +
                        "le_Dialog_ClickOkMouseButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string PresenterUserSettingsRightAdvanced_ShowDialogToUser__st__ {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAdvanced_ShowDialogToUser__st__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :s in the Web Browser?.
        /// </summary>
        public static string PresenterUserSettingsRightAdvanced_ShowDialogToUser_browser_ {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAdvanced_ShowDialogToUser_browser_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to open .
        /// </summary>
        public static string PresenterUserSettingsRightAdvanced_ShowDialogToUser_Open_ {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAdvanced_ShowDialogToUser_Open_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm.
        /// </summary>
        public static string PresenterUserSettingsRightAdvanced_ShowDialogToUser_Please_confirm {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAdvanced_ShowDialogToUser_Please_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV file | Macvendor.csv.
        /// </summary>
        public static string PresenterUserSettingsRightAdvanced_View_ReplaceClickMenu_CSV_file___Macvendor_csvl {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAdvanced_View_ReplaceClickMenu_CSV_file___Macvendor_csv" +
                        "l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;:.
        /// </summary>
        public static string PresenterUserSettingsRightAutoShownTabs_Dialog_ClickOkMouseButton___ {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAutoShownTabs_Dialog_ClickOkMouseButton___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.Please edit / insert the RegEx* to be associated with: &quot;.
        /// </summary>
        public static string PresenterUserSettingsRightAutoShownTabs_Dialog_ClickOkMouseButton__2_Please_edit___insert_the_RegEx_to_be_associated_with___ {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAutoShownTabs_Dialog_ClickOkMouseButton__2_Please_edit_" +
                        "__insert_the_RegEx_to_be_associated_with___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured in the user setting when setting a new item to listbox: .
        /// </summary>
        public static string PresenterUserSettingsRightAutoShownTabs_InsertItemsListbox_An_error_occured_in_the_user_setting_when_setting_a_new_item_to_listbox__ {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAutoShownTabs_InsertItemsListbox_An_error_occured_in_th" +
                        "e_user_setting_when_setting_a_new_item_to_listbox__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClipboardHelperRegEx error.
        /// </summary>
        public static string PresenterUserSettingsRightAutoShownTabs_InsertItemsListbox_Clipboard_Helper_error {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAutoShownTabs_InsertItemsListbox_Clipboard_Helper_error" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;:.
        /// </summary>
        public static string PresenterUserSettingsRightAutoShownTabs_UpdateListboxRightText___ {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAutoShownTabs_UpdateListboxRightText___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;:.
        /// </summary>
        public static string PresenterUserSettingsRightAutoShownTabs_ViewRules_RegExStringTextChanged___ {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAutoShownTabs_ViewRules_RegExStringTextChanged___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [RegEx is valid].
        /// </summary>
        public static string PresenterUserSettingsRightAutoShownTabs_ViewRules_RegExStringTextChanged___RegEx_is_valid_ {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAutoShownTabs_ViewRules_RegExStringTextChanged___RegEx_" +
                        "is_valid_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [RegEx not valid].
        /// </summary>
        public static string PresenterUserSettingsRightAutoShownTabs_ViewRules_RegExStringTextChanged___RegEx_not_valid_ {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAutoShownTabs_ViewRules_RegExStringTextChanged___RegEx_" +
                        "not_valid_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. When Clipboard text content changes and RegEx for: &quot;.
        /// </summary>
        public static string PresenterUserSettingsRightAutoShownTabs_ViewRules_RegExStringTextChanged__3__When_Clipboard_text_content_changes_and_RegEx_for___ {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAutoShownTabs_ViewRules_RegExStringTextChanged__3__When" +
                        "_Clipboard_text_content_changes_and_RegEx_for___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;:.
        /// </summary>
        public static string PresenterUserSettingsRightAutoShownTabs_ViewRules_RuleNamesSelectionChanged___ {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAutoShownTabs_ViewRules_RuleNamesSelectionChanged___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; functions correctly by inserting:.
        /// </summary>
        public static string PresenterUserSettingsRightAutoShownTabs_ViewRules_RuleNamesSelectionChanged___functions_correctly_by_inserting_ {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAutoShownTabs_ViewRules_RuleNamesSelectionChanged___fun" +
                        "ctions_correctly_by_inserting_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; matches with it, please insert what is shown:.
        /// </summary>
        public static string PresenterUserSettingsRightAutoShownTabs_ViewRules_RuleNamesSelectionChanged___matches_with_it__please_insert_what_is_shown_ {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAutoShownTabs_ViewRules_RuleNamesSelectionChanged___mat" +
                        "ches_with_it__please_insert_what_is_shown_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. When Clipboard text content changes and RegEx for Tab: &quot;.
        /// </summary>
        public static string PresenterUserSettingsRightAutoShownTabs_ViewRules_RuleNamesSelectionChanged__3__When_Clipboard_text_content_changes_and_RegEx_for_Tab___ {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAutoShownTabs_ViewRules_RuleNamesSelectionChanged__3__W" +
                        "hen_Clipboard_text_content_changes_and_RegEx_for_Tab___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help: Test if the regEx rule for Tab: &quot;.
        /// </summary>
        public static string PresenterUserSettingsRightAutoShownTabs_ViewRules_RuleNamesSelectionChanged_Help__Test_if_the_regEx_rule_for_Tab___ {
            get {
                return ResourceManager.GetString("PresenterUserSettingsRightAutoShownTabs_ViewRules_RuleNamesSelectionChanged_Help_" +
                        "_Test_if_the_regEx_rule_for_Tab___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        /// </summary>
        public static string Program_ApplicationOnThreadException {
            get {
                return ResourceManager.GetString("Program_ApplicationOnThreadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        /// </summary>
        public static string Program_CurrentDomainOnUnhandledException {
            get {
                return ResourceManager.GetString("Program_CurrentDomainOnUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClipboardHelperRegEx.
        /// </summary>
        public static string Program_Main_Clipboard_Helper {
            get {
                return ResourceManager.GetString("Program_Main_Clipboard_Helper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot run more than one instance of this application..
        /// </summary>
        public static string Program_Main_You_cannot_run_more_than_one_instance_of_this_application_ {
            get {
                return ResourceManager.GetString("Program_Main_You_cannot_run_more_than_one_instance_of_this_application_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RightArrow {
            get {
                object obj = ResourceManager.GetObject("RightArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RightArrowSelected {
            get {
                object obj = ResourceManager.GetObject("RightArrowSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClipboardHelperRegEx information.
        /// </summary>
        public static string SetTextClipboard_SetText_Clipboard_Helper_information {
            get {
                return ResourceManager.GetString("SetTextClipboard_SetText_Clipboard_Helper_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Clipboard could not set text..
        /// </summary>
        public static string SetTextClipboard_SetText_Windows_Clipboard_could_not_set_text_ {
            get {
                return ResourceManager.GetString("SetTextClipboard_SetText_Windows_Clipboard_could_not_set_text_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xml.
        /// </summary>
        public static string SettingsServiceXmlSerialization_AutoShownTabs__xml {
            get {
                return ResourceManager.GetString("SettingsServiceXmlSerialization_AutoShownTabs__xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClipboardHelperRegEx detected a corrupt xml data file in: 
        ///
        ///.
        /// </summary>
        public static string SettingsServiceXmlSerialization_ManuallyShownTabs_ {
            get {
                return ResourceManager.GetString("SettingsServiceXmlSerialization_ManuallyShownTabs_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .error..
        /// </summary>
        public static string SettingsServiceXmlSerialization_ManuallyShownTabs__error_ {
            get {
                return ResourceManager.GetString("SettingsServiceXmlSerialization_ManuallyShownTabs__error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClipboardHelperRegEx Error.
        /// </summary>
        public static string SettingsServiceXmlSerialization_ManuallyShownTabs_Clipboard_Helper_Error {
            get {
                return ResourceManager.GetString("SettingsServiceXmlSerialization_ManuallyShownTabs_Clipboard_Helper_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClipboardHelperRegEx.
        /// </summary>
        public static string ShortcutKeys_AddShortcutKey_ClipboardHelper {
            get {
                return ResourceManager.GetString("ShortcutKeys_AddShortcutKey_ClipboardHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t set Shortcut-key. Another app is probably using it. Please change the key combination..
        /// </summary>
        public static string ShortcutKeys_AddShortcutKey_Couldn_t_set_Shortcut_key__Another_app_is_probably_using_it__Please_change_the_key_combination_ {
            get {
                return ResourceManager.GetString("ShortcutKeys_AddShortcutKey_Couldn_t_set_Shortcut_key__Another_app_is_probably_us" +
                        "ing_it__Please_change_the_key_combination_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Unlocked {
            get {
                object obj = ResourceManager.GetObject("Unlocked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UnlockedSelected {
            get {
                object obj = ResourceManager.GetObject("UnlockedSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while replacing xml data file. Replacement has been aborted: 
        ///
        ///.
        /// </summary>
        public static string ValidateXml_Validate_ {
            get {
                return ResourceManager.GetString("ValidateXml_Validate_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClipboardHelperRegEx Xml file validation failed.
        /// </summary>
        public static string ValidateXml_Validate_Clipboard_Helper_Xml_file_validation_failed {
            get {
                return ResourceManager.GetString("ValidateXml_Validate_Clipboard_Helper_Xml_file_validation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Validation error: .
        /// </summary>
        public static string ValidateXml_ValidationCallBack_ {
            get {
                return ResourceManager.GetString("ValidateXml_ValidationCallBack_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner: .
        /// </summary>
        public static string ViewAbout_SetCompany_Owner__ {
            get {
                return ResourceManager.GetString("ViewAbout_SetCompany_Owner__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string ViewAbout_SetVersion_Version__ {
            get {
                return ResourceManager.GetString("ViewAbout_SetVersion_Version__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClipboardHelperRegEx - Settings.
        /// </summary>
        public static string ViewUserSettings_InitiateControls_Settings {
            get {
                return ResourceManager.GetString("ViewUserSettings_InitiateControls_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings:.
        /// </summary>
        public static string ViewUserSettings_InitiateControls_Settings_ {
            get {
                return ResourceManager.GetString("ViewUserSettings_InitiateControls_Settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ViewUserSettingsDownButtons_CreateControls_Apply {
            get {
                return ResourceManager.GetString("ViewUserSettingsDownButtons_CreateControls_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ViewUserSettingsDownButtons_CreateControls_Cancel {
            get {
                return ResourceManager.GetString("ViewUserSettingsDownButtons_CreateControls_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ViewUserSettingsDownButtons_CreateControls_Save {
            get {
                return ResourceManager.GetString("ViewUserSettingsDownButtons_CreateControls_Save", resourceCulture);
            }
        }
    }
}
