//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipboardHelperRegEx.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool appearanceWaitUntilFade {
            get {
                return ((bool)(this["appearanceWaitUntilFade"]));
            }
            set {
                this["appearanceWaitUntilFade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("385, 730")]
        public global::System.Drawing.Size sizeMain {
            get {
                return ((global::System.Drawing.Size)(this["sizeMain"]));
            }
            set {
                this["sizeMain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z")]
        public string appearanceSelectedKey {
            get {
                return ((string)(this["appearanceSelectedKey"]));
            }
            set {
                this["appearanceSelectedKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Minimize")]
        public string appearanceFadeChoices {
            get {
                return ((string)(this["appearanceFadeChoices"]));
            }
            set {
                this["appearanceFadeChoices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool appearanceFocus {
            get {
                return ((bool)(this["appearanceFocus"]));
            }
            set {
                this["appearanceFocus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool appearanceOpenBrowser {
            get {
                return ((bool)(this["appearanceOpenBrowser"]));
            }
            set {
                this["appearanceOpenBrowser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool appearanceCTRL {
            get {
                return ((bool)(this["appearanceCTRL"]));
            }
            set {
                this["appearanceCTRL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool appearanceALT {
            get {
                return ((bool)(this["appearanceALT"]));
            }
            set {
                this["appearanceALT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool appearanceSHIFT {
            get {
                return ((bool)(this["appearanceSHIFT"]));
            }
            set {
                this["appearanceSHIFT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool appearanceWIN {
            get {
                return ((bool)(this["appearanceWIN"]));
            }
            set {
                this["appearanceWIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int appearanceSecondsShowing {
            get {
                return ((int)(this["appearanceSecondsShowing"]));
            }
            set {
                this["appearanceSecondsShowing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400, 400")]
        public global::System.Drawing.Point location {
            get {
                return ((global::System.Drawing.Point)(this["location"]));
            }
            set {
                this["location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool appearanceAutostart {
            get {
                return ((bool)(this["appearanceAutostart"]));
            }
            set {
                this["appearanceAutostart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool locked {
            get {
                return ((bool)(this["locked"]));
            }
            set {
                this["locked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700, 423")]
        public global::System.Drawing.Size sizeUserSettings {
            get {
                return ((global::System.Drawing.Size)(this["sizeUserSettings"]));
            }
            set {
                this["sizeUserSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 14")]
        public global::System.Drawing.Size sizeMin {
            get {
                return ((global::System.Drawing.Size)(this["sizeMin"]));
            }
            set {
                this["sizeMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("449, 229")]
        public global::System.Drawing.Size sizeAbout {
            get {
                return ((global::System.Drawing.Size)(this["sizeAbout"]));
            }
            set {
                this["sizeAbout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("314, 113")]
        public global::System.Drawing.Size sizeWarning {
            get {
                return ((global::System.Drawing.Size)(this["sizeWarning"]));
            }
            set {
                this["sizeWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool activated {
            get {
                return ((bool)(this["activated"]));
            }
            set {
                this["activated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Excel")]
        public string appearanceFormattingExclusions {
            get {
                return ((string)(this["appearanceFormattingExclusions"]));
            }
            set {
                this["appearanceFormattingExclusions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DeepSkyBlue")]
        public global::System.Drawing.Color appearanceColorInfo {
            get {
                return ((global::System.Drawing.Color)(this["appearanceColorInfo"]));
            }
            set {
                this["appearanceColorInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Title")]
        public string appearanceColorChoices {
            get {
                return ((string)(this["appearanceColorChoices"]));
            }
            set {
                this["appearanceColorChoices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SkyBlue")]
        public global::System.Drawing.Color appearanceColorOutlookSearch {
            get {
                return ((global::System.Drawing.Color)(this["appearanceColorOutlookSearch"]));
            }
            set {
                this["appearanceColorOutlookSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightSteelBlue")]
        public global::System.Drawing.Color appearanceColorTitle {
            get {
                return ((global::System.Drawing.Color)(this["appearanceColorTitle"]));
            }
            set {
                this["appearanceColorTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SteelBlue")]
        public global::System.Drawing.Color appearanceColorWebUrlGoTo {
            get {
                return ((global::System.Drawing.Color)(this["appearanceColorWebUrlGoTo"]));
            }
            set {
                this["appearanceColorWebUrlGoTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color appearanceColorSelection {
            get {
                return ((global::System.Drawing.Color)(this["appearanceColorSelection"]));
            }
            set {
                this["appearanceColorSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MobaXterm;mRemoteNG;PuTTY;ConEmu64")]
        public string appearanceProgramsAlternativePasting {
            get {
                return ((string)(this["appearanceProgramsAlternativePasting"]));
            }
            set {
                this["appearanceProgramsAlternativePasting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection advancedFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["advancedFiles"]));
            }
            set {
                this["advancedFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstTimeRunForThisVersion {
            get {
                return ((bool)(this["FirstTimeRunForThisVersion"]));
            }
            set {
                this["FirstTimeRunForThisVersion"] = value;
            }
        }
    }
}
